"""initial phase 1 schema

Revision ID: 0001
Revises:
Create Date: 2026-07-25 14:49:10.769499
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from backend.app.data.types import UTCDateTime

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counterparties",
        sa.Column("counterparty_id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("counterparty_id", name=op.f("pk_counterparties")),
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", UTCDateTime(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'closed')",
            name=op.f("ck_customers_valid_customer_status"),
        ),
        sa.PrimaryKeyConstraint("customer_id", name=op.f("pk_customers")),
    )
    op.create_table(
        "dataset_runs",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("run_kind", sa.String(length=32), nullable=False),
        sa.Column("generator_version", sa.String(length=64), nullable=True),
        sa.Column("alembic_revision", sa.String(length=64), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=True),
        sa.Column("split_name", sa.String(length=32), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("record_counts", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(length=32), nullable=False),
        sa.CheckConstraint(
            "run_kind IN ('aml_seed', 'ml_prepare')", name=op.f("ck_dataset_runs_valid_run_kind")
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_dataset_runs")),
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=128), nullable=False),
        sa.Column("device_type", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", UTCDateTime(length=32), nullable=False),
        sa.Column("last_seen_at", UTCDateTime(length=32), nullable=False),
        sa.CheckConstraint(
            "last_seen_at >= first_seen_at", name=op.f("ck_devices_valid_device_interval")
        ),
        sa.PrimaryKeyConstraint("device_id", name=op.f("pk_devices")),
    )
    op.create_table(
        "investigations",
        sa.Column("investigation_id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("route", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", UTCDateTime(length=32), nullable=False),
        sa.Column("completed_at", UTCDateTime(length=32), nullable=True),
        sa.PrimaryKeyConstraint("investigation_id", name=op.f("pk_investigations")),
        sa.UniqueConstraint("request_id", name=op.f("uq_investigations_request_id")),
    )
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("customer_id", sa.String(length=128), nullable=False),
        sa.Column("account_type", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("opened_at", UTCDateTime(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'closed')",
            name=op.f("ck_accounts_valid_account_status"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_accounts_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("account_id", name=op.f("pk_accounts")),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index("ix_accounts_customer", ["customer_id"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=128), nullable=True),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_tier", sa.String(length=16), nullable=False),
        sa.Column("escalation_action", sa.String(length=16), nullable=False),
        sa.Column("evidence_snapshot_ref", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("created_at", UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", UTCDateTime(length=32), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'in_review', 'escalated', 'dismissed', 'closed')",
            name=op.f("ck_alerts_valid_alert_status"),
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.investigation_id"],
            name=op.f("fk_alerts_investigation_id_investigations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("alert_id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_alerts_idempotency_key")),
    )
    op.create_table(
        "customer_profiles",
        sa.Column("profile_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer_id", sa.String(length=128), nullable=False),
        sa.Column("segment", sa.String(length=16), nullable=False),
        sa.Column("residence_country", sa.String(length=2), nullable=False),
        sa.Column("occupation_or_industry", sa.String(length=128), nullable=True),
        sa.Column("declared_annual_income_minor", sa.Integer(), nullable=True),
        sa.Column("declared_revenue_band", sa.String(length=64), nullable=True),
        sa.Column("income_currency", sa.String(length=3), nullable=True),
        sa.Column("expected_monthly_volume_min_minor", sa.Integer(), nullable=True),
        sa.Column("expected_monthly_volume_max_minor", sa.Integer(), nullable=True),
        sa.Column("volume_currency", sa.String(length=3), nullable=True),
        sa.Column("kyc_risk_rating", sa.String(length=16), nullable=True),
        sa.Column("pep_flag", sa.Boolean(), nullable=False),
        sa.Column("profile_effective_from", UTCDateTime(length=32), nullable=False),
        sa.Column("profile_effective_to", UTCDateTime(length=32), nullable=True),
        sa.Column("profile_source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "kyc_risk_rating IS NULL OR kyc_risk_rating IN ('low', 'medium', 'high')",
            name=op.f("ck_customer_profiles_valid_kyc_rating"),
        ),
        sa.CheckConstraint(
            "segment IN ('retail', 'sme', 'corporate')",
            name=op.f("ck_customer_profiles_valid_segment"),
        ),
        sa.CheckConstraint(
            "expected_monthly_volume_max_minor IS NULL OR "
            "expected_monthly_volume_max_minor >= expected_monthly_volume_min_minor",
            name=op.f("ck_customer_profiles_ordered_expected_volume"),
        ),
        sa.CheckConstraint(
            "expected_monthly_volume_min_minor IS NULL OR expected_monthly_volume_min_minor >= 0",
            name=op.f("ck_customer_profiles_nonnegative_expected_min"),
        ),
        sa.CheckConstraint(
            "profile_effective_to IS NULL OR profile_effective_to > profile_effective_from",
            name=op.f("ck_customer_profiles_valid_profile_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_customer_profiles_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_customer_profiles")),
    )
    with op.batch_alter_table("customer_profiles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_profile_customer_effective", ["customer_id", "profile_effective_from"], unique=False
        )

    op.create_table(
        "alert_events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("alert_id", sa.String(length=128), nullable=False),
        sa.Column("timestamp", UTCDateTime(length=32), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("evidence_version", sa.String(length=64), nullable=False),
        sa.Column("risk_policy_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.alert_id"],
            name=op.f("fk_alert_events_alert_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_alert_events")),
    )
    with op.batch_alter_table("alert_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_alert_events_alert_timestamp", ["alert_id", "timestamp"], unique=False
        )

    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.String(length=128), nullable=False),
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("customer_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", UTCDateTime(length=32), nullable=False),
        sa.Column("posted_at", UTCDateTime(length=32), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("transaction_type", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("counterparty_id", sa.String(length=128), nullable=True),
        sa.Column("counterparty_account_id", sa.String(length=128), nullable=True),
        sa.Column("device_id", sa.String(length=128), nullable=True),
        sa.Column("ml_eligible", sa.Boolean(), nullable=False),
        sa.Column("ml_feature_ref", sa.String(length=128), nullable=True),
        sa.Column("data_source", sa.String(length=32), nullable=False),
        sa.Column("seed_run_id", sa.String(length=128), nullable=False),
        sa.CheckConstraint(
            "data_source IN ('synthetic', 'ulb_attached')",
            name=op.f("ck_transactions_valid_data_source"),
        ),
        sa.CheckConstraint(
            "direction IN ('credit', 'debit')", name=op.f("ck_transactions_valid_direction")
        ),
        sa.CheckConstraint(
            "(ml_eligible = 0 AND ml_feature_ref IS NULL) OR "
            "(ml_eligible = 1 AND ml_feature_ref IS NOT NULL)",
            name=op.f("ck_transactions_valid_ml_reference"),
        ),
        sa.CheckConstraint("amount_minor >= 0", name=op.f("ck_transactions_nonnegative_amount")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["counterparty_id"],
            ["counterparties.counterparty_id"],
            name=op.f("fk_transactions_counterparty_id_counterparties"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
            name=op.f("fk_transactions_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.device_id"],
            name=op.f("fk_transactions_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["seed_run_id"],
            ["dataset_runs.run_id"],
            name=op.f("fk_transactions_seed_run_id_dataset_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("pk_transactions")),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_txn_account_occurred", ["account_id", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_txn_amount", ["amount_minor"], unique=False)
        batch_op.create_index("ix_txn_country", ["country"], unique=False)
        batch_op.create_index(
            "ix_txn_customer_occurred", ["customer_id", "occurred_at"], unique=False
        )
        batch_op.create_index("ix_txn_ml_eligible", ["ml_eligible"], unique=False)
        batch_op.create_index("ix_txn_occurred_at", ["occurred_at"], unique=False)
        batch_op.create_index("ix_txn_type", ["transaction_type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_txn_type")
        batch_op.drop_index("ix_txn_occurred_at")
        batch_op.drop_index("ix_txn_ml_eligible")
        batch_op.drop_index("ix_txn_customer_occurred")
        batch_op.drop_index("ix_txn_country")
        batch_op.drop_index("ix_txn_amount")
        batch_op.drop_index("ix_txn_account_occurred")

    op.drop_table("transactions")
    with op.batch_alter_table("alert_events", schema=None) as batch_op:
        batch_op.drop_index("ix_alert_events_alert_timestamp")

    op.drop_table("alert_events")
    with op.batch_alter_table("customer_profiles", schema=None) as batch_op:
        batch_op.drop_index("ix_profile_customer_effective")

    op.drop_table("customer_profiles")
    op.drop_table("alerts")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index("ix_accounts_customer")

    op.drop_table("accounts")
    op.drop_table("investigations")
    op.drop_table("devices")
    op.drop_table("dataset_runs")
    op.drop_table("customers")
    op.drop_table("counterparties")
    # ### end Alembic commands ###
